# .readthedocs.yaml
version: 2

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Python environment
python:
  version: 3.12
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
